import streamlit as st
import pandas as pd
from services.parser_service import parse_extracted_biomarkers, parse_diet_sections


def format_status_badge(val: str) -> str:
    """Formats biomarker status string with styled badge."""
    if val == "HIGH":
        return '<span class="status-badge-high">🔴 HIGH</span>'
    elif val == "LOW":
        return '<span class="status-badge-low">🟡 LOW</span>'
    elif val == "NORMAL":
        return '<span class="status-badge-normal">🟢 NORMAL</span>'
    return val


def render_dashboard(extracted_values: str, diet_summary: str):
    """Renders the diagnostic & nutrition analysis dashboard."""
    st.markdown("---")
    st.subheader("2. Diagnostic & Nutrition Analysis Dashboard")

    df_results = parse_extracted_biomarkers(extracted_values)
    summary_text, avoid_text, eat_text = parse_diet_sections(diet_summary)

    # 1. Metrics Strip
    if not df_results.empty and "Status" in df_results.columns:
        total_tests = len(df_results)
        high_count = int((df_results["Status"] == "HIGH").sum())
        low_count = int((df_results["Status"] == "LOW").sum())
        normal_count = int((df_results["Status"] == "NORMAL").sum())

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Total Biomarkers", total_tests)
        with col2:
            st.metric("Normal Parameters", normal_count, delta="Normal", delta_color="normal")
        with col3:
            st.metric("Elevated (HIGH)", high_count, delta=f"{high_count} Alert" if high_count > 0 else None, delta_color="inverse")
        with col4:
            st.metric("Deficient (LOW)", low_count, delta=f"{low_count} Alert" if low_count > 0 else None, delta_color="inverse")

    # 2. Output Tabs
    tab_tests, tab_summary, tab_diet, tab_raw = st.tabs([
        "📊 Extracted Test Values",
        "🩺 Patient Health Summary",
        "🥗 Indian Diet Plan",
        "📑 Raw Outputs & Export"
    ])

    # Tab 1: Extracted Test Values
    with tab_tests:
        if not df_results.empty:
            st.markdown("#### Test Biomarker Classifications")

            filter_col1, filter_col2 = st.columns([2, 2])
            with filter_col1:
                status_filter = st.selectbox(
                    "Filter by Status:",
                    options=["All", "Abnormal Only (HIGH / LOW)", "HIGH", "LOW", "NORMAL"],
                    index=0
                )
            with filter_col2:
                search_query = st.text_input("🔍 Search Test Name:", placeholder="e.g. Cholesterol, Glucose, ALT...")

            # Apply filters
            filtered_df = df_results.copy()
            if status_filter == "Abnormal Only (HIGH / LOW)":
                filtered_df = filtered_df[filtered_df["Status"].isin(["HIGH", "LOW"])]
            elif status_filter in ["HIGH", "LOW", "NORMAL"]:
                filtered_df = filtered_df[filtered_df["Status"] == status_filter]

            if search_query.strip():
                filtered_df = filtered_df[filtered_df["Test Name"].str.contains(search_query.strip(), case=False, na=False)]

            display_df = filtered_df.copy()
            display_df["Status Badge"] = display_df["Status"].apply(format_status_badge)

            st.write(
                display_df[["Test Name", "Measured Value", "Status Badge", "Reference Range"]]
                .to_html(escape=False, index=False),
                unsafe_allow_html=True
            )
            st.caption(f"Showing {len(display_df)} of {len(df_results)} extracted biomarkers.")
        else:
            st.markdown(extracted_values)

    # Tab 2: Health Summary
    with tab_summary:
        st.markdown("#### 🩺 Clinical Insights & Patient Condition")
        if summary_text:
            st.info(summary_text)
        else:
            st.info(diet_summary)

    # Tab 3: Indian Diet Plan
    with tab_diet:
        st.markdown("#### 🥗 Tailored Indian Dietary Recommendations")
        if avoid_text or eat_text:
            diet_col1, diet_col2 = st.columns(2)
            with diet_col1:
                with st.container(border=True):
                    st.markdown("### 🚫 Food to Avoid")
                    st.markdown(avoid_text if avoid_text else "No specific food items to avoid listed.")
            with diet_col2:
                with st.container(border=True):
                    st.markdown("### 🥗 Food to Eat More Of")
                    st.markdown(eat_text if eat_text else "No specific foods to eat more of listed.")
        else:
            with st.container(border=True):
                st.markdown(diet_summary)

    # Tab 4: Raw Outputs & Export
    with tab_raw:
        st.markdown("#### 📑 Full Generated Report")
        
        full_report_content = f"""# Blood Work & Indian Diet Analysis Report

## 1. Extracted Lab Parameters
{extracted_values}

## 2. Health Summary & Indian Diet Plan
{diet_summary}

---
*Disclaimer: Generated by Blood Work AI. This report is for informational purposes only. Consult a doctor for medical decisions.*
"""
        st.text_area("Full Markdown Content", value=full_report_content, height=250)

        # Download Buttons
        dl_col1, dl_col2 = st.columns(2)
        with dl_col1:
            st.download_button(
                label="📥 Download Analysis Report (.md)",
                data=full_report_content,
                file_name="blood_work_analysis_report.md",
                mime="text/markdown",
                use_container_width=True
            )
        with dl_col2:
            if not df_results.empty:
                csv_data = df_results.to_csv(index=False)
                st.download_button(
                    label="📊 Download Extracted Biomarkers (.csv)",
                    data=csv_data,
                    file_name="blood_test_biomarkers.csv",
                    mime="text/csv",
                    use_container_width=True
                )

