import streamlit as st
import pandas as pd
from services.parser_service import parse_extracted_tests, parse_diet_sections


def format_status_badge(val: str) -> str:
    """Formats test status string with standardized pill badges."""
    if val == "HIGH":
        return '<span class="status-badge-high">HIGH</span>'
    elif val == "LOW":
        return '<span class="status-badge-low">LOW</span>'
    elif val == "NORMAL":
        return '<span class="status-badge-normal">NORMAL</span>'
    return f'<span>{val}</span>'


def render_dashboard(extracted_values: str, diet_summary: str):
    """Renders the diagnostic and nutrition analysis dashboard."""
    st.markdown("---")
    st.subheader("2. Diagnostic Analysis & Clinical Recommendations")

    df_results = parse_extracted_tests(extracted_values)
    summary_text, avoid_text, eat_text = parse_diet_sections(diet_summary)

    # 1. Metrics Strip
    if not df_results.empty and "Status" in df_results.columns:
        total_tests = len(df_results)
        high_count = int((df_results["Status"] == "HIGH").sum())
        low_count = int((df_results["Status"] == "LOW").sum())
        normal_count = int((df_results["Status"] == "NORMAL").sum())

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Total Parameters", total_tests)
        with col2:
            st.metric("Within Reference Range", normal_count)
        with col3:
            st.metric("Elevated Parameters", high_count)
        with col4:
            st.metric("Low Parameters", low_count)

    # 2. Output Tabs
    tab_tests, tab_summary, tab_diet, tab_raw = st.tabs([
        "Test Results",
        "Clinical Summary",
        "Dietary Protocol",
        "Complete Report & Export"
    ])

    # Tab 1: Extracted Test Values
    with tab_tests:
        if not df_results.empty:
            st.markdown("#### Laboratory Test Results")

            display_df = df_results.copy()
            display_df["Status Classification"] = display_df["Status"].apply(format_status_badge)

            st.write(
                display_df[["Test Name", "Measured Value", "Status Classification", "Reference Range"]]
                .to_html(escape=False, index=False),
                unsafe_allow_html=True
            )
            st.caption(f"Total: {len(df_results)} laboratory test parameters evaluated.")
        else:
            st.markdown(extracted_values)

    # Tab 2: Health Summary
    with tab_summary:
        st.markdown("#### Clinical Health Summary")
        if summary_text:
            st.info(summary_text)
        else:
            st.info(diet_summary)

    # Tab 3: Indian Diet Plan
    with tab_diet:
        st.markdown("#### Targeted Indian Dietary Protocol")
        if avoid_text or eat_text:
            diet_col1, diet_col2 = st.columns(2)
            with diet_col1:
                with st.container(border=True):
                    st.markdown("### Foods to Avoid")
                    st.markdown(avoid_text if avoid_text else "No specific restrictions noted.")
            with diet_col2:
                with st.container(border=True):
                    st.markdown("### Recommended Foods to Include")
                    st.markdown(eat_text if eat_text else "No specific recommendations noted.")
        else:
            with st.container(border=True):
                st.markdown(diet_summary)

    # Tab 4: Raw Outputs & Export
    with tab_raw:
        st.markdown("#### Diagnostic Report Summary")
        
        full_report_content = f"""# Clinical Blood Work & Dietary Analysis Report

## 1. Extracted Laboratory Parameters
{extracted_values}

## 2. Clinical Health Summary & Dietary Plan
{diet_summary}

---
*Disclaimer: Generated by Blood Work AI. This report is for educational and informational purposes only. Consult a certified medical professional for diagnostic interpretation.*
"""
        st.text_area("Markdown Report Content", value=full_report_content, height=250)

        # Download Buttons
        dl_col1, dl_col2 = st.columns(2)
        with dl_col1:
            st.download_button(
                label="Download Report (.md)",
                data=full_report_content,
                file_name="blood_work_analysis_report.md",
                mime="text/markdown",
                use_container_width=True
            )
        with dl_col2:
            if not df_results.empty:
                csv_data = df_results.to_csv(index=False)
                st.download_button(
                    label="Download Test Results (.csv)",
                    data=csv_data,
                    file_name="blood_test_results.csv",
                    mime="text/csv",
                    use_container_width=True
                )
